_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
colsample_bytree:
    value: 0.6446374160498977
eval_metric:
    value: auc
gamma:
    value: 3.8166434618541083
learning_rate:
    value: 0.01324742513935051
max_depth:
    value: 3
min_child_weight:
    value: 8
model_name:
    value: XGBoost
n_estimators:
    value: 1200
output_dir:
    value: /home/matangold/ydata/models
reg_alpha:
    value: 0.5
reg_lambda:
    value: 0.30000000000000004
scale_pos_weight:
    value: 12.83147256362707
subsample:
    value: 0.762002220741562
test_path:
    value: /home/matangold/ydata/data/test.csv
train_path:
    value: /home/matangold/ydata/data/train.csv
